'env':
  'BASE_IMAGE': |-
    ${{ vars.BASE_IMAGE || 'adguard/go-builder:1.26.5--1' }}
  'DIST_DIR': |-
    dist
'jobs':
  'BuildBinaries':
    'if': |
      ${{ github.repository_owner == 'AdGuardSoftwareLimited' }}
    'permissions':
      'contents': 'read'
    'runs-on': 'team-go'
    'steps':
      - 'uses': 'actions/checkout@v6'
        'with':
          # Set to false to avoid GITHUB_TOKEN leaking.
          #
          # See https://github.com/actions/checkout/issues/485#issuecomment-934422611.
          'persist-credentials': false
      - 'name': 'Set source date epoch'
        'run': |
          echo "SOURCE_DATE_EPOCH=$(git log -1 --format=%ct)" >> "$GITHUB_ENV"
      - 'name': 'Build'
        'uses': 'AdGuardSoftwareLimited/actions/actions/docker-build@master'
        'with':
          'dockerfile': 'docker/ci.Dockerfile'
          'context': '.'
          'target': 'qa-builder-exporter'
          'output': '.'
          'build-args': |
            APP_VERSION=${{ github.ref_name }}
            BASE_IMAGE=${{ env.BASE_IMAGE }}
            BRANCH=${{ github.ref_name }}
            CACHE_BUSTER=${{ inputs.cache_buster || '0' }}
            CHANNEL="development"
            DIST_DIR=${{ env.DIST_DIR }}
            REVISION=${{ github.sha }}
            SIGN=0
            SOURCE_DATE_EPOCH=${{ env.SOURCE_DATE_EPOCH }}
      - 'uses': 'actions/upload-artifact@v7'
        'with':
          'name': 'adguarddnscli'
          'path': |
            ${{ env.DIST_DIR }}
          # TODO(d.kolyshev):  Sign QA builds.
'name': 'Build QA Artifacts'
'on':
  'push':
    'branches':
      - '*'
  'workflow_dispatch':
    'inputs':
      'cache_buster':
        'default': ''
        'description': |
          Override to force re-run of cached stages (pass any unique value).
        'type': 'string'
# Permissions are disabled for all the jobs by default, and then overridden for
# specific jobs if needed.  This is a recommended practice for security reasons,
# and also allows to avoid mistakes with permissions when creating new jobs.
#
# See https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#permissions.
'permissions': {}
