'env':
  'BASE_IMAGE': |-
    ${{ vars.BASE_IMAGE || 'adguard/go-builder:1.27.1--1' }}
  'CHANNEL': |-
    ${{ case(
      startsWith(github.head_ref, 'release-v'), 'release',
      startsWith(github.head_ref, 'rc-v'), 'candidate',
      'development'
    ) }}
  'DIST_DIR': |-
    dist
'jobs':
  'BuildBinaries':
    'if': |
      ${{ github.repository_owner == 'AdGuardSoftwareLimited' }}
    'outputs':
      'app_version': ${{ steps.set_envs.outputs.app_version }}
      'source_date_epoch': ${{ steps.set_envs.outputs.source_date_epoch }}
    'permissions':
      'contents': 'read'
      'id-token': 'write'
    'runs-on': 'team-go'
    'steps':
      - 'uses': 'actions/checkout@v6'
        'with':
          # Fetch all branches and tags to make the version script work.
          'fetch-depth': 0
          # Set to false to avoid GITHUB_TOKEN leaking.
          #
          # See https://github.com/actions/checkout/issues/485#issuecomment-934422611.
          'persist-credentials': false
      - 'name': "Set environment variables"
        'id': 'set_envs'
        'run': |
          source_date_epoch=$(git log -1 --format=%ct)
          readonly source_date_epoch

          echo "SOURCE_DATE_EPOCH=${source_date_epoch}" >> "$GITHUB_ENV"

          # Also expose the source date epoch as a job output, since the env
          # context is not available to the other jobs.
          echo "source_date_epoch=${source_date_epoch}" >> "$GITHUB_OUTPUT"

          app_version="$(env CHANNEL=${{ env.CHANNEL }} sh ./scripts/make/version.sh)"
          readonly app_version

          echo "APP_VERSION=${app_version}" >> "$GITHUB_ENV"

          # Also expose the version as a job output, since the env context is
          # not available to the other jobs.
          echo "app_version=${app_version}" >> "$GITHUB_OUTPUT"
      - 'name': 'Retrieve GPG signing secrets'
        'uses': 'hashicorp/vault-action@v4'
        'with':
          'url': ${{ vars.VAULT_URL }}
          'method': 'jwt'
          'role': 'gpg-signing'
          'secrets': |
            secret/data/ci-secrets/gpg-signing gpgPassword | GPG_PASSWORD ;
            secret/data/ci-secrets/gpg-signing gpgSecretKey | GPG_SECRET_KEY ;
      - 'name': 'Build Darwin'
        'uses': 'AdGuardSoftwareLimited/actions/actions/docker-build@master'
        'with':
          'dockerfile': 'docker/ci.Dockerfile'
          'context': '.'
          'target': 'builder-exporter'
          'output': '.'
          'build-args': |
            APP_VERSION=${{ env.APP_VERSION }}
            ARCH=amd64 arm64
            BASE_IMAGE=${{ env.BASE_IMAGE }}
            CACHE_BUSTER=${{ inputs.cache_buster || '0' }}
            CHANNEL=${{ env.CHANNEL }}
            DIST_DIR=${{ env.DIST_DIR }}
            OS=darwin
            REVISION=${{ github.sha }}
            SIGN=1
            SOURCE_DATE_EPOCH=${{ env.SOURCE_DATE_EPOCH }}
          'secrets': |
            GPG_KEY_PASSPHRASE=${{ env.GPG_PASSWORD }}
            GPG_SECRET_KEY=${{ env.GPG_SECRET_KEY }}
      - 'name': 'Build Linux'
        'uses': 'AdGuardSoftwareLimited/actions/actions/docker-build@master'
        'with':
          'dockerfile': 'docker/ci.Dockerfile'
          'context': '.'
          'target': 'builder-exporter'
          'output': '.'
          'build-args': |
            APP_VERSION=${{ env.APP_VERSION }}
            ARCH=amd64
            BASE_IMAGE=${{ env.BASE_IMAGE }}
            CACHE_BUSTER=${{ inputs.cache_buster || '0' }}
            CHANNEL=${{ env.CHANNEL }}
            DIST_DIR=${{ env.DIST_DIR }}
            OS=linux
            REVISION=${{ github.sha }}
            SIGN=1
            SOURCE_DATE_EPOCH=${{ env.SOURCE_DATE_EPOCH }}
          'secrets': |
            GPG_KEY_PASSPHRASE=${{ env.GPG_PASSWORD }}
            GPG_SECRET_KEY=${{ env.GPG_SECRET_KEY }}
      - 'name': 'Upload Unix releases'
        'uses': 'actions/upload-artifact@v7'
        'with':
          'name': 'adguarddnscli-qa-unix'
          'path': |
            ${{ env.DIST_DIR }}/*
      - 'name': 'Build Windows'
        'uses': 'AdGuardSoftwareLimited/actions/actions/docker-build@master'
        'with':
          'dockerfile': 'docker/ci.Dockerfile'
          'context': '.'
          'target': 'builder-exporter'
          'output': '.'
          'build-args': |
            APP_VERSION=${{ env.APP_VERSION }}
            ARCH=amd64
            BASE_IMAGE=${{ env.BASE_IMAGE }}
            CACHE_BUSTER=${{ inputs.cache_buster || '0' }}
            CHANNEL="development"
            DIST_DIR=${{ env.DIST_DIR }}
            OS=windows
            REVISION=${{ github.sha }}
            SIGN=0
            SOURCE_DATE_EPOCH=${{ env.SOURCE_DATE_EPOCH }}
      - 'name': 'Upload Windows releases'
        'uses': 'actions/upload-artifact@v7'
        'with':
          'name': 'adguarddnscli-qa-windows'
          'path': |
            ${{ env.DIST_DIR }}/AdGuardDNSCLI_windows_*
  'SignWindowsEXE':
    'name': 'Sign Windows executables'
    'needs': 'BuildBinaries'
    'if': |
      ${{ github.repository_owner == 'AdGuardSoftwareLimited' }}
    'permissions':
      'contents': 'read'
      'id-token': 'write'
    'uses': 'AdGuardSoftwareLimited/actions/.github/workflows/sign-by-signer.yml@master'
    'with':
      'team': 'go'
      'artifact-name': 'adguarddnscli-qa-windows'
      'files': 'AdGuardDNSCLI_windows_*/AdGuardDNSCLI/adguarddns-cli.exe'
      'signed-artifact-name': 'adguarddnscli-qa-windows'
  'BuildWindowsMSI':
    'name': 'Build Windows MSI'
    'needs':
      - 'BuildBinaries'
      - 'SignWindowsEXE'
    'if': |
      ${{ github.repository_owner == 'AdGuardSoftwareLimited' }}
    'permissions':
      'contents': 'read'
    'runs-on': 'team-go'
    'steps':
      - 'uses': 'actions/checkout@v6'
        'with':
          # Set to false to avoid GITHUB_TOKEN leaking.
          #
          # See https://github.com/actions/checkout/issues/485#issuecomment-934422611.
          'persist-credentials': false
      - 'name': 'Download signed Windows executables'
        'uses': 'actions/download-artifact@v8'
        'with':
          'name': 'adguarddnscli-qa-windows'
          'path': |
            ${{ env.DIST_DIR }}
      - 'name': 'Build MSI installer'
        'env':
          'APP_VERSION': ${{ needs.BuildBinaries.outputs.app_version }}
          'SOURCE_DATE_EPOCH': ${{ needs.BuildBinaries.outputs.source_date_epoch }}
        'uses': 'AdGuardSoftwareLimited/actions/actions/docker-build@master'
        'with':
          'dockerfile': 'docker/ci.Dockerfile'
          'context': '.'
          'target': 'msi-builder-exporter'
          'output': '.'
          'build-args': |
            APP_VERSION=${{ env.APP_VERSION }}
            ARCH=amd64
            CACHE_BUSTER=${{ inputs.cache_buster || '0' }}
            DIST_DIR=${{ env.DIST_DIR }}
            SOURCE_DATE_EPOCH=${{ env.SOURCE_DATE_EPOCH }}
      - 'name': 'Upload MSI installer'
        'uses': 'actions/upload-artifact@v7'
        'with':
          'name': 'adguarddnscli-qa-msi'
          'path': |
            ${{ env.DIST_DIR }}/AdGuardDNSCLI_windows_*.msi
  'SignWindowsMSI':
    'name': 'Sign Windows MSI'
    'needs': 'BuildWindowsMSI'
    'if': |
      ${{ github.repository_owner == 'AdGuardSoftwareLimited' }}
    'permissions':
      'contents': 'read'
      'id-token': 'write'
    'uses': 'AdGuardSoftwareLimited/actions/.github/workflows/sign-by-signer.yml@master'
    'with':
      'team': 'go'
      'artifact-name': 'adguarddnscli-qa-msi'
      'files': 'AdGuardDNSCLI_windows_*.msi'
      'signed-artifact-name': 'adguarddnscli-qa-msi'
  'PackArtifacts':
    'name': 'Pack artifacts'
    'needs':
      - 'BuildBinaries'
      - 'SignWindowsMSI'
    'if': |
      ${{ github.repository_owner == 'AdGuardSoftwareLimited' }}
    'permissions':
      'contents': 'read'
    'runs-on': 'team-go'
    'steps':
      - 'uses': 'actions/checkout@v6'
        'with':
          # Set to false to avoid GITHUB_TOKEN leaking.
          #
          # See https://github.com/actions/checkout/issues/485#issuecomment-934422611.
          'persist-credentials': false
      - 'name': 'Download Unix artifacts'
        'uses': 'actions/download-artifact@v8'
        'with':
          'name': 'adguarddnscli-qa-unix'
          'path': |
            ${{ env.DIST_DIR }}
      - 'name': 'Download MSI artifact'
        'uses': 'actions/download-artifact@v8'
        'with':
          'name': 'adguarddnscli-qa-msi'
          'path': |
            ${{ env.DIST_DIR }}
      - 'name': 'Pack'
        'env':
          'APP_VERSION': ${{needs.BuildBinaries.outputs.app_version}}
          'SOURCE_DATE_EPOCH': ${{ needs.BuildBinaries.outputs.source_date_epoch }}
        'uses': 'AdGuardSoftwareLimited/actions/actions/docker-build@master'
        'with':
          'dockerfile': 'docker/ci.Dockerfile'
          'context': '.'
          'target': 'packer-exporter'
          'output': '.'
          'build-args': |
            APP_VERSION=${{ env.APP_VERSION }}
            CACHE_BUSTER=${{ inputs.cache_buster || '0' }}
            DIST_DIR=${{ env.DIST_DIR }}
            SOURCE_DATE_EPOCH=${{ env.SOURCE_DATE_EPOCH }}
      - 'uses': 'actions/upload-artifact@v7'
        'with':
          'name': 'adguarddnscli-qa'
          'path': |
            ${{ env.DIST_DIR }}/*.*
'name': 'Build QA artifacts'
'on':
  'pull_request':
    'branches':
      - '*'
  'workflow_dispatch':
    'inputs':
      'cache_buster':
        'default': ''
        'description': |
          Override to force re-run of cached stages (pass any unique value).
        'type': 'string'
# Permissions are disabled for all the jobs by default, and then overridden for
# specific jobs if needed.  This is a recommended practice for security reasons,
# and also allows to avoid mistakes with permissions when creating new jobs.
#
# See https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#permissions.
'permissions': {}
